### ISSUE TITLE
sharing strategy for TrackScheme and BDV overlay settings

### ISSUE THREAD

**Issue by tpietzsch** [fiji/TrackMate3#23]
Currently it is a messy/undefined, how the settings are configured and applied with multiple trackscheme or BDV windows.

For example, if I open two TrackScheme windows each has it's own display settings and seetings dialog. If I change the definition of a custom style "mystyle" in one of the settings dialogs, this is not changed in the other dialog, and actually the only way to make this accessible in the other window is to save the settings to disk and close and re-open the window.

We need a central management of trackscheme styles.
Then, we need to decide, whether we want to
a) choose one style that applies for all windows, or
b) choose one style per window.
I think (a) makes more sense.

For the BDV overlays it is a different story. I think there users definitely could want to use different settings for different windows. Probably it would make sense to split the settings into two parts. One part is the same for all windows, e.g., colors and strokes. How long the edge "tails" are, etc, can change per window. Still, a style could set defaults for these but can be overridden per window?

**Comment by tinevez** [comment]
Hi would like to suggest another approach for the MaMuT-like application. 

I think we can keep one setting/style per window, but use settings persistence to have something user-friendly. For instance:
- the user has 2 BDV windows with settings 1 and 2.
- they save the project
- upon loading the project, 2 BDV windows are re-created with desired settings.

The same for TrackScheme.

**Comment by tinevez** [comment]
On another hand you correctly noted some bugs:

- [ ] No central management for BDV rendersettings.
- [ ] No central management for TrackScheme styles.

**Comment by tinevez** [comment]
We now have several display styles, managed in a preferences page.
