### ISSUE TITLE
Make the tagging of vertices and edges undoable. 

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate3#33]
As of now, only properties of the `Model` are undoable because the recorder are created at model construction time. 
`TagSet`s are based on `PropertyMap`s so they could be made undoable, but right now it does not work because they are not registered in the `GraphUndoRecorder`

**Comment by ctrueden** [comment]
Any chance we can generalize the undo logic so that all of ImageJ2 can benefit? Or is it too big of a project?

**Comment by tpietzsch** [comment]
@ctrueden Some notes explaining the mastodon undo framework: https://gist.github.com/tpietzsch/b597b2ad8062d52dcad375a810473523
It has kind of a "hybrid" undo history (as mentioned in imagej/imagej-common#3) so the general ideas seem applicable.
That being said, the mastodon undo framework is in its second (and possibly not final) iteration, still too rough that I would recommend it as a starting point for generalization.

**Comment by ctrueden** [comment]
> the mastodon undo framework is in its second (and possibly not final) iteration, still too rough that I would recommend it as a starting point for generalization.

Perhaps we could revisit then after it iterates a couple more times? Please just keep it in mind for the future of ImageJ2, that if you can make a general enough undo framework, we could push it to the SciJava layer in the future. Thanks guys!

**Comment by tinevez** [comment]
@tpietzsch We can close this issue right? You addressed it all in the last weeks if I remember correctly.

**Comment by tpietzsch** [comment]
👍
