### ISSUE TITLE
JVM crashes after modifying the graph in TrackScheme.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate3#34]
It can happen that the Mastodon crashes when modifying the graph several times via its highlight or focus. 

The diagnosis is as follow (based on the `unify-views` branch):

A `graphChanged` event ends up in calling the `paint()` method of the `TrackSchemePanel`.

The `paint()` method does mainly two things, in the following order:
  * It recompute the graph layout: All `TrackScheme` vertices get a new value for `X`. This calls the **`layout()`** method of the `LineageTreeLayout` class.
  * It regenerates the `ScreenEntities` for the new layout. This involves creating new `ScreenVertex`es and `ScreenEdge`s properly linked to the `TrackScheme` items currently displayed. This calls the **`cropAndScale()`** method of the `LineageTreeLayout` class.

  Between the call of **`layout()`** and **`cropAndScale()`**, the `ScreenEntities` are invalid. They may correspond to `TrackScheme` items that moved or disappeared because of the graph change event.

This issue is caused by the fact that several classes are notified when the **`layout()`** method is finished, and interrogate the `ScreenEntities`. For instance for this bug:

1. A `graphChanged` event ends up in calling the `paint()` method of the `TrackSchemePanel`.

1. The `paint()` method calls the `layout()` method of the `LineageTreeLayout` class.

1. When the layout is done, The `LayoutListener` of the class are notified (via `layoutChanged()). 

1. One of these listener is the `InertialScreenTransformListener`. It notifies its `TransformListener` (via `transformChanged()`).

1. This `transform listener is the `InteractiveDisplayCanvasComponent`. It has several listeners it forward this event to. 

1. One of them is the `MouseHighlightHandler`. Calling its `transformChanged()` method causes it to try an grab the currently highlighted edge or vertex.

1. To do so, it calls the `getEdgeAt()` or `getVertexAt()` method of the `AbstractTrackSchemeOverlay` class.

1. These two methods rely on `ScreenEntities` to retrieve the desired `TrackScheme` item, but at this time, they are not valid. They link to `TrackScheme` items that may have been deleted or moved. Calling a second graph modification event with these items is what causes the crash.

**Comment by tpietzsch** [comment]
@tinevez thanks for finding this out!

**Comment by tpietzsch** [comment]
@tinevez I have a tentative fix for this. It requires addition of a `RefPool.getIfExists()` method, so it touches all mastodon projects:

https://github.com/bigdataviewer/mastodon-collection/tree/safe-get-object
https://github.com/bigdataviewer/mastodon-graph/tree/safe-get-object
https://github.com/fiji/TrackMate3/tree/safe-get-object

Can you have a look? If everything is ok, I'll merge and release...

**Comment by tinevez** [comment]
Sorry for delayed response.

Yes it works! The crash is gone!
