### ISSUE TITLE
There should be a Kd-tree to search spot neighbors.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate3#4]
This is important for performance (_e.g._ GUI responsivity: we need to quickly retrieve the spot closest to a click location).

This is tricky, because we allow for incremental model changes. The Kd-tree cannot be recomputed for each single change, otherwise the performance will degrade quickly, which is not the desired effect. A system to cache changes must be implemented, which is another issue.

**Comment by tpietzsch** [comment]
all done

**Comment by ctrueden** [comment]
@tpietzsch Links please?

**Comment by tpietzsch** [comment]
https://github.com/fiji/TrackMate3/tree/master/src/main/java/net/trackmate/kdtree is the KDTree
https://github.com/fiji/TrackMate3/tree/master/src/main/java/net/trackmate/spatial is the search building on top of KDTree plus changes, in particular https://github.com/fiji/TrackMate3/blob/master/src/main/java/net/trackmate/spatial/SpatialIndexData.java

**Comment by ctrueden** [comment]
@tpietzsch Thanks!

**Comment by tpietzsch** [comment]
@ctrueden my pleasure! I didn't know that you were following TrackMate3.

**Comment by ctrueden** [comment]
> I didn't know that you were following TrackMate3.

Only very casually, unfortunately.

How come TrackMate3 needs a KDTree when ImgLib2 already has one? Different interfaces/frameworks/etc.?

There are quite a few KDTrees in this world. [Weka has one](http://git.imagej.net/git/?p=weka.git;a=blob;f=weka/src/main/java/weka/core/neighboursearch/KDTree.java;h=4e92846a632465e3871861d6c8d30fac7873042f;hb=HEAD). And [so does ThunderSTORM](https://github.com/zitmen/thunderstorm/blob/5555c073167843ebc8ca135fc6d7a989a2be697a/src/main/java/cz/cuni/lf1/lge/ThunderSTORM/util/javaml/kdtree/KDTree.java) though that one is lifted from Java ML.

**Comment by tpietzsch** [comment]
This KDTree has the same interfaces as imglib2's (or rather the searches on it have). The difference is the objects that are stored in it. TrackMate3 is heavily based on PoolObjects (conceptually similar to imglib2 types; stored in Pools mapping to primitive arrays, similar to imglib2 Imgs but always 1D and can grow dynamically). This KDTree plays nice with them. It also stores its nodes as PoolObjects avoiding creating many Objects as imglib2 KDTree does. But algorithms for building and searching the tree are pretty much the same.
