### ISSUE TITLE
idea: disable cmd+Q

### ISSUE THREAD

**Issue by xulman** [fiji/TrackMate3#64]
Hi,
don't remembering all shortcuts by heart (and being lazy and irresponsible -- by just trying keystrokes), happened to me a couple of times that I've killed completely Mastodon (and Fiji) by pressing Cmd+Q. I did that in an attempt to increase radius of a spot, which is decreased with Q and I did too much, and I was hoping that something like alt+q, shift+q, cmd+q might do the opposite...

BTW: Cmd+, opens also the Preference dialog of Fiji (the single check-box one with "Clear preferences").

Was on Mac.
Vlado

**Comment by ctrueden** [comment]
Firstly: shouldn't this issue be in imagej/imagej, since you're asking for a global disable of Cmd+Q for all of ImageJ?

Secondly: I was going to argue that we shouldn't override default Mac behavior. But then Chrome recently implemented a thing where you have to press Cmd+Q twice in order to really quit. So I guess we could do this... _if_ you can figure out how to override that shortcut on the Java side.

Otherwise, you can always override the Cmd+Q shortcut globally on your system using [some hack like this](https://apple.stackexchange.com/a/205742/137617).

**Comment by tinevez** [comment]
Please no hack....
As much as possible we do not want to mess with existing UIs.
If Shift+Q does not work for changing the spot size, please change the keymap now that it is possible in Mastodon.

**Comment by xulman** [comment]
To my defense :) It has not occurred to me that the fact that Fiji closes upon Cmd+Q is not due to Fiji's own will (which explains to me also why similar short cut does not close FIji in other OSes), but it's an Apple's goodie.

Shift+Q works, I guess, it is probably slow/fast radius decrease.. I wanted the radius increase. I now remember that E is the answer.

**Comment by xulman** [comment]
PS: If you would be interested in starting a discussion about changing a few default shortcuts (before Mastodon gets widespread), here's a couple of ideas:
* avoid using Cmd+whatever, I would stay with omnipresent shift, ctrl, alt only
* swap ctrl+A (add linked spot) with A (add spot), this saves one key stroke per timepoint per cell... at least I would always do: ctrl+A to start a track and follow cell with just A (not ctrl+A) and space/q/e to adjust, then A again...

**Comment by tinevez** [comment]
> * swap ctrl+A (add linked spot) with A (add spot), this saves one key stroke per timepoint per cell... at least I would always do: ctrl+A to start a track and follow cell with just A (not ctrl+A) and space/q/e to adjust, then A again...

Normally this is the case: to create a linked spot, just press 'A' inside an existing spot. Ctrl A should not do anything no?

**Comment by xulman** [comment]
![mastodon_keymap](https://user-images.githubusercontent.com/10509335/47458838-e46d2280-d7da-11e8-9074-1c6ef79cec30.png)

**Comment by xulman** [comment]
Hmm, I think I took the screen shot from already altered project..  sorry. With `Default (built in)` keymap, there is A for both `add linked spot` and `add spot`, and it works just fine (don't know what I was doing days back so that I adopted this habit of changing this shortcut). My bad, case closed.

Your favourite trouble maker,
V.
