### ISSUE TITLE
Imported TGMM data does not respond properly to zoom in the BigDataViewer panel

### ISSUE THREAD

**Issue by MLbyML** [fiji/TrackMate3#88]
Hello,

I noticed that upon importing some TGMM data into a Mastodon project, the number of green dots (where each green dot is a gaussian) appears to change if you zoom in and out -- this is probably a bug, since the number of gaussians should stay constant! 
I attach a figure showing this occurrence at three different zoom levels for the same time point.  
![threezoomlevels](https://user-images.githubusercontent.com/34229641/54088175-92790380-435b-11e9-9ce2-9e90239a1d88.png)
For your reference, my OS is Ubuntu 18.04. Thank you!

**Comment by tpietzsch** [comment]
This is the intended behaviour.
Everything up to a certain distance from the current viewing plane is visible.
In the preferences you can say what distance that is, and whether it is relative to the current zoom level or absolute ("view relative focus limit" checkbox). What you observe is consistent to "view relative focus limit" set to "on".
<img width="805" alt="Screenshot 2019-03-10 at 21 52 53" src="https://user-images.githubusercontent.com/622070/54091281-e517e700-437e-11e9-9f14-40027dbb7fcc.png">

**Comment by MLbyML** [comment]
Okay. Thank you very much for the information about the relative focus limit (exactly what I need)!  :)
